// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listitemsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _itemsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createitemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteitemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getitemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateitemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listrecipesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _recipesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createrecipeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleterecipeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrecipeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updaterecipeMw() []app.HandlerFunc {
	// your code...
	return nil
}
