// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package api

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type RecipeItemType int64

const (
	RecipeItemType_INPUT  RecipeItemType = 1
	RecipeItemType_OUTPUT RecipeItemType = 2
)

func (p RecipeItemType) String() string {
	switch p {
	case RecipeItemType_INPUT:
		return "INPUT"
	case RecipeItemType_OUTPUT:
		return "OUTPUT"
	}
	return "<UNSET>"
}

func RecipeItemTypeFromString(s string) (RecipeItemType, error) {
	switch s {
	case "INPUT":
		return RecipeItemType_INPUT, nil
	case "OUTPUT":
		return RecipeItemType_OUTPUT, nil
	}
	return RecipeItemType(0), fmt.Errorf("not a valid RecipeItemType string")
}

func RecipeItemTypePtr(v RecipeItemType) *RecipeItemType { return &v }
func (p *RecipeItemType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = RecipeItemType(result.Int64)
	return
}

func (p *RecipeItemType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

// Common response structure
type BaseResponse struct {
	Code    int32  `thrift:"code,1,required" form:"code,required" json:"code,required" query:"code,required"`
	Message string `thrift:"message,2,required" form:"message,required" json:"message,required" query:"message,required"`
}

func NewBaseResponse() *BaseResponse {
	return &BaseResponse{}
}

func (p *BaseResponse) InitDefault() {
}

func (p *BaseResponse) GetCode() (v int32) {
	return p.Code
}

func (p *BaseResponse) GetMessage() (v string) {
	return p.Message
}

func (p *BaseResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResponse(%+v)", *p)
}

// Item related structures
type Item struct {
	ID        int64  `thrift:"id,1,required" form:"id,required" json:"id,required" query:"id,required"`
	Name      string `thrift:"name,2,required" form:"name,required" json:"name,required" query:"name,required"`
	CreatedAt string `thrift:"created_at,3,required" form:"created_at,required" json:"created_at,required" query:"created_at,required"`
	UpdatedAt string `thrift:"updated_at,4,required" form:"updated_at,required" json:"updated_at,required" query:"updated_at,required"`
}

func NewItem() *Item {
	return &Item{}
}

func (p *Item) InitDefault() {
}

func (p *Item) GetID() (v int64) {
	return p.ID
}

func (p *Item) GetName() (v string) {
	return p.Name
}

func (p *Item) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *Item) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *Item) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Item(%+v)", *p)
}

type CreateItemReq struct {
	Name string `thrift:"name,1,required" form:"name,required" json:"name,required"`
}

func NewCreateItemReq() *CreateItemReq {
	return &CreateItemReq{}
}

func (p *CreateItemReq) InitDefault() {
}

func (p *CreateItemReq) GetName() (v string) {
	return p.Name
}

func (p *CreateItemReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateItemReq(%+v)", *p)
}

type CreateItemResp struct {
	Base *BaseResponse `thrift:"base,1,required" form:"base,required" json:"base,required" query:"base,required"`
	Data *Item         `thrift:"data,2,required" form:"data,required" json:"data,required" query:"data,required"`
}

func NewCreateItemResp() *CreateItemResp {
	return &CreateItemResp{}
}

func (p *CreateItemResp) InitDefault() {
}

var CreateItemResp_Base_DEFAULT *BaseResponse

func (p *CreateItemResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return CreateItemResp_Base_DEFAULT
	}
	return p.Base
}

var CreateItemResp_Data_DEFAULT *Item

func (p *CreateItemResp) GetData() (v *Item) {
	if !p.IsSetData() {
		return CreateItemResp_Data_DEFAULT
	}
	return p.Data
}

func (p *CreateItemResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *CreateItemResp) IsSetData() bool {
	return p.Data != nil
}

func (p *CreateItemResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateItemResp(%+v)", *p)
}

type GetItemReq struct {
	ID int64 `thrift:"id,1,required" json:"id,required" path:"id,required"`
}

func NewGetItemReq() *GetItemReq {
	return &GetItemReq{}
}

func (p *GetItemReq) InitDefault() {
}

func (p *GetItemReq) GetID() (v int64) {
	return p.ID
}

func (p *GetItemReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetItemReq(%+v)", *p)
}

type GetItemResp struct {
	Base *BaseResponse `thrift:"base,1,required" form:"base,required" json:"base,required" query:"base,required"`
	Data *Item         `thrift:"data,2,required" form:"data,required" json:"data,required" query:"data,required"`
}

func NewGetItemResp() *GetItemResp {
	return &GetItemResp{}
}

func (p *GetItemResp) InitDefault() {
}

var GetItemResp_Base_DEFAULT *BaseResponse

func (p *GetItemResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return GetItemResp_Base_DEFAULT
	}
	return p.Base
}

var GetItemResp_Data_DEFAULT *Item

func (p *GetItemResp) GetData() (v *Item) {
	if !p.IsSetData() {
		return GetItemResp_Data_DEFAULT
	}
	return p.Data
}

func (p *GetItemResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetItemResp) IsSetData() bool {
	return p.Data != nil
}

func (p *GetItemResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetItemResp(%+v)", *p)
}

type UpdateItemReq struct {
	ID   int64  `thrift:"id,1,required" json:"id,required" path:"id,required"`
	Name string `thrift:"name,2,required" form:"name,required" json:"name,required"`
}

func NewUpdateItemReq() *UpdateItemReq {
	return &UpdateItemReq{}
}

func (p *UpdateItemReq) InitDefault() {
}

func (p *UpdateItemReq) GetID() (v int64) {
	return p.ID
}

func (p *UpdateItemReq) GetName() (v string) {
	return p.Name
}

func (p *UpdateItemReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateItemReq(%+v)", *p)
}

type UpdateItemResp struct {
	Base *BaseResponse `thrift:"base,1,required" form:"base,required" json:"base,required" query:"base,required"`
	Data *Item         `thrift:"data,2,required" form:"data,required" json:"data,required" query:"data,required"`
}

func NewUpdateItemResp() *UpdateItemResp {
	return &UpdateItemResp{}
}

func (p *UpdateItemResp) InitDefault() {
}

var UpdateItemResp_Base_DEFAULT *BaseResponse

func (p *UpdateItemResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return UpdateItemResp_Base_DEFAULT
	}
	return p.Base
}

var UpdateItemResp_Data_DEFAULT *Item

func (p *UpdateItemResp) GetData() (v *Item) {
	if !p.IsSetData() {
		return UpdateItemResp_Data_DEFAULT
	}
	return p.Data
}

func (p *UpdateItemResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpdateItemResp) IsSetData() bool {
	return p.Data != nil
}

func (p *UpdateItemResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateItemResp(%+v)", *p)
}

type DeleteItemReq struct {
	ID int64 `thrift:"id,1,required" json:"id,required" path:"id,required"`
}

func NewDeleteItemReq() *DeleteItemReq {
	return &DeleteItemReq{}
}

func (p *DeleteItemReq) InitDefault() {
}

func (p *DeleteItemReq) GetID() (v int64) {
	return p.ID
}

func (p *DeleteItemReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteItemReq(%+v)", *p)
}

type DeleteItemResp struct {
	Base *BaseResponse `thrift:"base,1,required" form:"base,required" json:"base,required" query:"base,required"`
}

func NewDeleteItemResp() *DeleteItemResp {
	return &DeleteItemResp{}
}

func (p *DeleteItemResp) InitDefault() {
}

var DeleteItemResp_Base_DEFAULT *BaseResponse

func (p *DeleteItemResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return DeleteItemResp_Base_DEFAULT
	}
	return p.Base
}

func (p *DeleteItemResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *DeleteItemResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteItemResp(%+v)", *p)
}

type ListItemsReq struct {
	Page  *int32  `thrift:"page,1,optional" json:"page,omitempty" query:"page"`
	Limit *int32  `thrift:"limit,2,optional" json:"limit,omitempty" query:"limit"`
	Name  *string `thrift:"name,3,optional" json:"name,omitempty" query:"name"`
}

func NewListItemsReq() *ListItemsReq {
	return &ListItemsReq{}
}

func (p *ListItemsReq) InitDefault() {
}

var ListItemsReq_Page_DEFAULT int32

func (p *ListItemsReq) GetPage() (v int32) {
	if !p.IsSetPage() {
		return ListItemsReq_Page_DEFAULT
	}
	return *p.Page
}

var ListItemsReq_Limit_DEFAULT int32

func (p *ListItemsReq) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return ListItemsReq_Limit_DEFAULT
	}
	return *p.Limit
}

var ListItemsReq_Name_DEFAULT string

func (p *ListItemsReq) GetName() (v string) {
	if !p.IsSetName() {
		return ListItemsReq_Name_DEFAULT
	}
	return *p.Name
}

func (p *ListItemsReq) IsSetPage() bool {
	return p.Page != nil
}

func (p *ListItemsReq) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *ListItemsReq) IsSetName() bool {
	return p.Name != nil
}

func (p *ListItemsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListItemsReq(%+v)", *p)
}

type ListItemsResp struct {
	Base  *BaseResponse `thrift:"base,1,required" form:"base,required" json:"base,required" query:"base,required"`
	Data  []*Item       `thrift:"data,2,required" form:"data,required" json:"data,required" query:"data,required"`
	Total int32         `thrift:"total,3,required" form:"total,required" json:"total,required" query:"total,required"`
}

func NewListItemsResp() *ListItemsResp {
	return &ListItemsResp{}
}

func (p *ListItemsResp) InitDefault() {
}

var ListItemsResp_Base_DEFAULT *BaseResponse

func (p *ListItemsResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return ListItemsResp_Base_DEFAULT
	}
	return p.Base
}

func (p *ListItemsResp) GetData() (v []*Item) {
	return p.Data
}

func (p *ListItemsResp) GetTotal() (v int32) {
	return p.Total
}

func (p *ListItemsResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListItemsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListItemsResp(%+v)", *p)
}

// Recipe related structures
type Recipe struct {
	ID         int64   `thrift:"id,1,required" form:"id,required" json:"id,required" query:"id,required"`
	Space      int64   `thrift:"space,2,required" form:"space,required" json:"space,required" query:"space,required"`
	ItemID     int64   `thrift:"item_id,3,required" form:"item_id,required" json:"item_id,required" query:"item_id,required"`
	Efficiency float64 `thrift:"efficiency,4,required" form:"efficiency,required" json:"efficiency,required" query:"efficiency,required"`
	CreatedAt  string  `thrift:"created_at,5,required" form:"created_at,required" json:"created_at,required" query:"created_at,required"`
	UpdatedAt  string  `thrift:"updated_at,6,required" form:"updated_at,required" json:"updated_at,required" query:"updated_at,required"`
}

func NewRecipe() *Recipe {
	return &Recipe{}
}

func (p *Recipe) InitDefault() {
}

func (p *Recipe) GetID() (v int64) {
	return p.ID
}

func (p *Recipe) GetSpace() (v int64) {
	return p.Space
}

func (p *Recipe) GetItemID() (v int64) {
	return p.ItemID
}

func (p *Recipe) GetEfficiency() (v float64) {
	return p.Efficiency
}

func (p *Recipe) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *Recipe) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *Recipe) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Recipe(%+v)", *p)
}

type RecipeItem struct {
	ID        int64          `thrift:"id,1,required" form:"id,required" json:"id,required" query:"id,required"`
	RecipeID  int64          `thrift:"recipe_id,2,required" form:"recipe_id,required" json:"recipe_id,required" query:"recipe_id,required"`
	Space     int64          `thrift:"space,3,required" form:"space,required" json:"space,required" query:"space,required"`
	Type      RecipeItemType `thrift:"type,4,required" form:"type,required" json:"type,required" query:"type,required"`
	ItemID    int64          `thrift:"item_id,5,required" form:"item_id,required" json:"item_id,required" query:"item_id,required"`
	Count     int32          `thrift:"count,6,required" form:"count,required" json:"count,required" query:"count,required"`
	CreatedAt string         `thrift:"created_at,7,required" form:"created_at,required" json:"created_at,required" query:"created_at,required"`
	UpdatedAt string         `thrift:"updated_at,8,required" form:"updated_at,required" json:"updated_at,required" query:"updated_at,required"`
}

func NewRecipeItem() *RecipeItem {
	return &RecipeItem{}
}

func (p *RecipeItem) InitDefault() {
}

func (p *RecipeItem) GetID() (v int64) {
	return p.ID
}

func (p *RecipeItem) GetRecipeID() (v int64) {
	return p.RecipeID
}

func (p *RecipeItem) GetSpace() (v int64) {
	return p.Space
}

func (p *RecipeItem) GetType() (v RecipeItemType) {
	return p.Type
}

func (p *RecipeItem) GetItemID() (v int64) {
	return p.ItemID
}

func (p *RecipeItem) GetCount() (v int32) {
	return p.Count
}

func (p *RecipeItem) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *RecipeItem) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *RecipeItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecipeItem(%+v)", *p)
}

type CreateRecipeReq struct {
	Space      int64         `thrift:"space,1,required" form:"space,required" json:"space,required"`
	ItemID     int64         `thrift:"item_id,2,required" form:"item_id,required" json:"item_id,required"`
	Efficiency float64       `thrift:"efficiency,3,required" form:"efficiency,required" json:"efficiency,required"`
	Items      []*RecipeItem `thrift:"items,4,required" form:"items,required" json:"items,required"`
}

func NewCreateRecipeReq() *CreateRecipeReq {
	return &CreateRecipeReq{}
}

func (p *CreateRecipeReq) InitDefault() {
}

func (p *CreateRecipeReq) GetSpace() (v int64) {
	return p.Space
}

func (p *CreateRecipeReq) GetItemID() (v int64) {
	return p.ItemID
}

func (p *CreateRecipeReq) GetEfficiency() (v float64) {
	return p.Efficiency
}

func (p *CreateRecipeReq) GetItems() (v []*RecipeItem) {
	return p.Items
}

func (p *CreateRecipeReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateRecipeReq(%+v)", *p)
}

type CreateRecipeResp struct {
	Base *BaseResponse `thrift:"base,1,required" form:"base,required" json:"base,required" query:"base,required"`
	Data *Recipe       `thrift:"data,2,required" form:"data,required" json:"data,required" query:"data,required"`
}

func NewCreateRecipeResp() *CreateRecipeResp {
	return &CreateRecipeResp{}
}

func (p *CreateRecipeResp) InitDefault() {
}

var CreateRecipeResp_Base_DEFAULT *BaseResponse

func (p *CreateRecipeResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return CreateRecipeResp_Base_DEFAULT
	}
	return p.Base
}

var CreateRecipeResp_Data_DEFAULT *Recipe

func (p *CreateRecipeResp) GetData() (v *Recipe) {
	if !p.IsSetData() {
		return CreateRecipeResp_Data_DEFAULT
	}
	return p.Data
}

func (p *CreateRecipeResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *CreateRecipeResp) IsSetData() bool {
	return p.Data != nil
}

func (p *CreateRecipeResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateRecipeResp(%+v)", *p)
}

type GetRecipeReq struct {
	ID int64 `thrift:"id,1,required" json:"id,required" path:"id,required"`
}

func NewGetRecipeReq() *GetRecipeReq {
	return &GetRecipeReq{}
}

func (p *GetRecipeReq) InitDefault() {
}

func (p *GetRecipeReq) GetID() (v int64) {
	return p.ID
}

func (p *GetRecipeReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetRecipeReq(%+v)", *p)
}

type GetRecipeResp struct {
	Base  *BaseResponse `thrift:"base,1,required" form:"base,required" json:"base,required" query:"base,required"`
	Data  *Recipe       `thrift:"data,2,required" form:"data,required" json:"data,required" query:"data,required"`
	Items []*RecipeItem `thrift:"items,3,required" form:"items,required" json:"items,required" query:"items,required"`
}

func NewGetRecipeResp() *GetRecipeResp {
	return &GetRecipeResp{}
}

func (p *GetRecipeResp) InitDefault() {
}

var GetRecipeResp_Base_DEFAULT *BaseResponse

func (p *GetRecipeResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return GetRecipeResp_Base_DEFAULT
	}
	return p.Base
}

var GetRecipeResp_Data_DEFAULT *Recipe

func (p *GetRecipeResp) GetData() (v *Recipe) {
	if !p.IsSetData() {
		return GetRecipeResp_Data_DEFAULT
	}
	return p.Data
}

func (p *GetRecipeResp) GetItems() (v []*RecipeItem) {
	return p.Items
}

func (p *GetRecipeResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetRecipeResp) IsSetData() bool {
	return p.Data != nil
}

func (p *GetRecipeResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetRecipeResp(%+v)", *p)
}

type UpdateRecipeReq struct {
	ID         int64         `thrift:"id,1,required" json:"id,required" path:"id,required"`
	Space      *int64        `thrift:"space,2,optional" form:"space" json:"space,omitempty"`
	ItemID     *int64        `thrift:"item_id,3,optional" form:"item_id" json:"item_id,omitempty"`
	Efficiency *float64      `thrift:"efficiency,4,optional" form:"efficiency" json:"efficiency,omitempty"`
	Items      []*RecipeItem `thrift:"items,5,optional" form:"items" json:"items,omitempty"`
}

func NewUpdateRecipeReq() *UpdateRecipeReq {
	return &UpdateRecipeReq{}
}

func (p *UpdateRecipeReq) InitDefault() {
}

func (p *UpdateRecipeReq) GetID() (v int64) {
	return p.ID
}

var UpdateRecipeReq_Space_DEFAULT int64

func (p *UpdateRecipeReq) GetSpace() (v int64) {
	if !p.IsSetSpace() {
		return UpdateRecipeReq_Space_DEFAULT
	}
	return *p.Space
}

var UpdateRecipeReq_ItemID_DEFAULT int64

func (p *UpdateRecipeReq) GetItemID() (v int64) {
	if !p.IsSetItemID() {
		return UpdateRecipeReq_ItemID_DEFAULT
	}
	return *p.ItemID
}

var UpdateRecipeReq_Efficiency_DEFAULT float64

func (p *UpdateRecipeReq) GetEfficiency() (v float64) {
	if !p.IsSetEfficiency() {
		return UpdateRecipeReq_Efficiency_DEFAULT
	}
	return *p.Efficiency
}

var UpdateRecipeReq_Items_DEFAULT []*RecipeItem

func (p *UpdateRecipeReq) GetItems() (v []*RecipeItem) {
	if !p.IsSetItems() {
		return UpdateRecipeReq_Items_DEFAULT
	}
	return p.Items
}

func (p *UpdateRecipeReq) IsSetSpace() bool {
	return p.Space != nil
}

func (p *UpdateRecipeReq) IsSetItemID() bool {
	return p.ItemID != nil
}

func (p *UpdateRecipeReq) IsSetEfficiency() bool {
	return p.Efficiency != nil
}

func (p *UpdateRecipeReq) IsSetItems() bool {
	return p.Items != nil
}

func (p *UpdateRecipeReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateRecipeReq(%+v)", *p)
}

type UpdateRecipeResp struct {
	Base *BaseResponse `thrift:"base,1,required" form:"base,required" json:"base,required" query:"base,required"`
	Data *Recipe       `thrift:"data,2,required" form:"data,required" json:"data,required" query:"data,required"`
}

func NewUpdateRecipeResp() *UpdateRecipeResp {
	return &UpdateRecipeResp{}
}

func (p *UpdateRecipeResp) InitDefault() {
}

var UpdateRecipeResp_Base_DEFAULT *BaseResponse

func (p *UpdateRecipeResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return UpdateRecipeResp_Base_DEFAULT
	}
	return p.Base
}

var UpdateRecipeResp_Data_DEFAULT *Recipe

func (p *UpdateRecipeResp) GetData() (v *Recipe) {
	if !p.IsSetData() {
		return UpdateRecipeResp_Data_DEFAULT
	}
	return p.Data
}

func (p *UpdateRecipeResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpdateRecipeResp) IsSetData() bool {
	return p.Data != nil
}

func (p *UpdateRecipeResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateRecipeResp(%+v)", *p)
}

type DeleteRecipeReq struct {
	ID int64 `thrift:"id,1,required" json:"id,required" path:"id,required"`
}

func NewDeleteRecipeReq() *DeleteRecipeReq {
	return &DeleteRecipeReq{}
}

func (p *DeleteRecipeReq) InitDefault() {
}

func (p *DeleteRecipeReq) GetID() (v int64) {
	return p.ID
}

func (p *DeleteRecipeReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteRecipeReq(%+v)", *p)
}

type DeleteRecipeResp struct {
	Base *BaseResponse `thrift:"base,1,required" form:"base,required" json:"base,required" query:"base,required"`
}

func NewDeleteRecipeResp() *DeleteRecipeResp {
	return &DeleteRecipeResp{}
}

func (p *DeleteRecipeResp) InitDefault() {
}

var DeleteRecipeResp_Base_DEFAULT *BaseResponse

func (p *DeleteRecipeResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return DeleteRecipeResp_Base_DEFAULT
	}
	return p.Base
}

func (p *DeleteRecipeResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *DeleteRecipeResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteRecipeResp(%+v)", *p)
}

type ListRecipesReq struct {
	Page   *int32 `thrift:"page,1,optional" json:"page,omitempty" query:"page"`
	Limit  *int32 `thrift:"limit,2,optional" json:"limit,omitempty" query:"limit"`
	Space  *int64 `thrift:"space,3,optional" json:"space,omitempty" query:"space"`
	ItemID *int64 `thrift:"item_id,4,optional" json:"item_id,omitempty" query:"item_id"`
}

func NewListRecipesReq() *ListRecipesReq {
	return &ListRecipesReq{}
}

func (p *ListRecipesReq) InitDefault() {
}

var ListRecipesReq_Page_DEFAULT int32

func (p *ListRecipesReq) GetPage() (v int32) {
	if !p.IsSetPage() {
		return ListRecipesReq_Page_DEFAULT
	}
	return *p.Page
}

var ListRecipesReq_Limit_DEFAULT int32

func (p *ListRecipesReq) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return ListRecipesReq_Limit_DEFAULT
	}
	return *p.Limit
}

var ListRecipesReq_Space_DEFAULT int64

func (p *ListRecipesReq) GetSpace() (v int64) {
	if !p.IsSetSpace() {
		return ListRecipesReq_Space_DEFAULT
	}
	return *p.Space
}

var ListRecipesReq_ItemID_DEFAULT int64

func (p *ListRecipesReq) GetItemID() (v int64) {
	if !p.IsSetItemID() {
		return ListRecipesReq_ItemID_DEFAULT
	}
	return *p.ItemID
}

func (p *ListRecipesReq) IsSetPage() bool {
	return p.Page != nil
}

func (p *ListRecipesReq) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *ListRecipesReq) IsSetSpace() bool {
	return p.Space != nil
}

func (p *ListRecipesReq) IsSetItemID() bool {
	return p.ItemID != nil
}

func (p *ListRecipesReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListRecipesReq(%+v)", *p)
}

type ListRecipesResp struct {
	Base  *BaseResponse `thrift:"base,1,required" form:"base,required" json:"base,required" query:"base,required"`
	Data  []*Recipe     `thrift:"data,2,required" form:"data,required" json:"data,required" query:"data,required"`
	Total int32         `thrift:"total,3,required" form:"total,required" json:"total,required" query:"total,required"`
}

func NewListRecipesResp() *ListRecipesResp {
	return &ListRecipesResp{}
}

func (p *ListRecipesResp) InitDefault() {
}

var ListRecipesResp_Base_DEFAULT *BaseResponse

func (p *ListRecipesResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return ListRecipesResp_Base_DEFAULT
	}
	return p.Base
}

func (p *ListRecipesResp) GetData() (v []*Recipe) {
	return p.Data
}

func (p *ListRecipesResp) GetTotal() (v int32) {
	return p.Total
}

func (p *ListRecipesResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListRecipesResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListRecipesResp(%+v)", *p)
}

// Service definitions
type ItemService interface {
	CreateItem(ctx context.Context, request *CreateItemReq) (r *CreateItemResp, err error)

	GetItem(ctx context.Context, request *GetItemReq) (r *GetItemResp, err error)

	UpdateItem(ctx context.Context, request *UpdateItemReq) (r *UpdateItemResp, err error)

	DeleteItem(ctx context.Context, request *DeleteItemReq) (r *DeleteItemResp, err error)

	ListItems(ctx context.Context, request *ListItemsReq) (r *ListItemsResp, err error)
}

type RecipeService interface {
	CreateRecipe(ctx context.Context, request *CreateRecipeReq) (r *CreateRecipeResp, err error)

	GetRecipe(ctx context.Context, request *GetRecipeReq) (r *GetRecipeResp, err error)

	UpdateRecipe(ctx context.Context, request *UpdateRecipeReq) (r *UpdateRecipeResp, err error)

	DeleteRecipe(ctx context.Context, request *DeleteRecipeReq) (r *DeleteRecipeResp, err error)

	ListRecipes(ctx context.Context, request *ListRecipesReq) (r *ListRecipesResp, err error)
}
