// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package api

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type RecipeItemType int64

const (
	RecipeItemType_INPUT  RecipeItemType = 1
	RecipeItemType_OUTPUT RecipeItemType = 2
)

func (p RecipeItemType) String() string {
	switch p {
	case RecipeItemType_INPUT:
		return "INPUT"
	case RecipeItemType_OUTPUT:
		return "OUTPUT"
	}
	return "<UNSET>"
}

func RecipeItemTypeFromString(s string) (RecipeItemType, error) {
	switch s {
	case "INPUT":
		return RecipeItemType_INPUT, nil
	case "OUTPUT":
		return RecipeItemType_OUTPUT, nil
	}
	return RecipeItemType(0), fmt.Errorf("not a valid RecipeItemType string")
}

func RecipeItemTypePtr(v RecipeItemType) *RecipeItemType { return &v }
func (p *RecipeItemType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = RecipeItemType(result.Int64)
	return
}

func (p *RecipeItemType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

// Common response structure
type BaseResponse struct {
	Code    *int32  `thrift:"code,1,optional" form:"code" json:"code,omitempty" query:"code"`
	Message *string `thrift:"message,2,optional" form:"message" json:"message,omitempty" query:"message"`
}

func NewBaseResponse() *BaseResponse {
	return &BaseResponse{}
}

func (p *BaseResponse) InitDefault() {
}

var BaseResponse_Code_DEFAULT int32

func (p *BaseResponse) GetCode() (v int32) {
	if !p.IsSetCode() {
		return BaseResponse_Code_DEFAULT
	}
	return *p.Code
}

var BaseResponse_Message_DEFAULT string

func (p *BaseResponse) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return BaseResponse_Message_DEFAULT
	}
	return *p.Message
}

func (p *BaseResponse) IsSetCode() bool {
	return p.Code != nil
}

func (p *BaseResponse) IsSetMessage() bool {
	return p.Message != nil
}

func (p *BaseResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResponse(%+v)", *p)
}

// Item related structures
type Item struct {
	ID        *int64  `thrift:"id,1,optional" form:"id" json:"id,omitempty" query:"id"`
	Name      *string `thrift:"name,2,optional" form:"name" json:"name,omitempty" query:"name"`
	CreatedAt *string `thrift:"created_at,3,optional" form:"created_at" json:"created_at,omitempty" query:"created_at"`
	UpdatedAt *string `thrift:"updated_at,4,optional" form:"updated_at" json:"updated_at,omitempty" query:"updated_at"`
}

func NewItem() *Item {
	return &Item{}
}

func (p *Item) InitDefault() {
}

var Item_ID_DEFAULT int64

func (p *Item) GetID() (v int64) {
	if !p.IsSetID() {
		return Item_ID_DEFAULT
	}
	return *p.ID
}

var Item_Name_DEFAULT string

func (p *Item) GetName() (v string) {
	if !p.IsSetName() {
		return Item_Name_DEFAULT
	}
	return *p.Name
}

var Item_CreatedAt_DEFAULT string

func (p *Item) GetCreatedAt() (v string) {
	if !p.IsSetCreatedAt() {
		return Item_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var Item_UpdatedAt_DEFAULT string

func (p *Item) GetUpdatedAt() (v string) {
	if !p.IsSetUpdatedAt() {
		return Item_UpdatedAt_DEFAULT
	}
	return *p.UpdatedAt
}

func (p *Item) IsSetID() bool {
	return p.ID != nil
}

func (p *Item) IsSetName() bool {
	return p.Name != nil
}

func (p *Item) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *Item) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *Item) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Item(%+v)", *p)
}

type CreateItemReq struct {
	Name *string `thrift:"name,1,optional" form:"name" json:"name,omitempty"`
}

func NewCreateItemReq() *CreateItemReq {
	return &CreateItemReq{}
}

func (p *CreateItemReq) InitDefault() {
}

var CreateItemReq_Name_DEFAULT string

func (p *CreateItemReq) GetName() (v string) {
	if !p.IsSetName() {
		return CreateItemReq_Name_DEFAULT
	}
	return *p.Name
}

func (p *CreateItemReq) IsSetName() bool {
	return p.Name != nil
}

func (p *CreateItemReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateItemReq(%+v)", *p)
}

type CreateItemResp struct {
	Base *BaseResponse `thrift:"base,1,optional" form:"base" json:"base,omitempty" query:"base"`
	Data *Item         `thrift:"data,2,optional" form:"data" json:"data,omitempty" query:"data"`
}

func NewCreateItemResp() *CreateItemResp {
	return &CreateItemResp{}
}

func (p *CreateItemResp) InitDefault() {
}

var CreateItemResp_Base_DEFAULT *BaseResponse

func (p *CreateItemResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return CreateItemResp_Base_DEFAULT
	}
	return p.Base
}

var CreateItemResp_Data_DEFAULT *Item

func (p *CreateItemResp) GetData() (v *Item) {
	if !p.IsSetData() {
		return CreateItemResp_Data_DEFAULT
	}
	return p.Data
}

func (p *CreateItemResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *CreateItemResp) IsSetData() bool {
	return p.Data != nil
}

func (p *CreateItemResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateItemResp(%+v)", *p)
}

type GetItemReq struct {
	ID *int64 `thrift:"id,1,optional" json:"id,omitempty" path:"id"`
}

func NewGetItemReq() *GetItemReq {
	return &GetItemReq{}
}

func (p *GetItemReq) InitDefault() {
}

var GetItemReq_ID_DEFAULT int64

func (p *GetItemReq) GetID() (v int64) {
	if !p.IsSetID() {
		return GetItemReq_ID_DEFAULT
	}
	return *p.ID
}

func (p *GetItemReq) IsSetID() bool {
	return p.ID != nil
}

func (p *GetItemReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetItemReq(%+v)", *p)
}

type GetItemResp struct {
	Base *BaseResponse `thrift:"base,1,optional" form:"base" json:"base,omitempty" query:"base"`
	Data *Item         `thrift:"data,2,optional" form:"data" json:"data,omitempty" query:"data"`
}

func NewGetItemResp() *GetItemResp {
	return &GetItemResp{}
}

func (p *GetItemResp) InitDefault() {
}

var GetItemResp_Base_DEFAULT *BaseResponse

func (p *GetItemResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return GetItemResp_Base_DEFAULT
	}
	return p.Base
}

var GetItemResp_Data_DEFAULT *Item

func (p *GetItemResp) GetData() (v *Item) {
	if !p.IsSetData() {
		return GetItemResp_Data_DEFAULT
	}
	return p.Data
}

func (p *GetItemResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetItemResp) IsSetData() bool {
	return p.Data != nil
}

func (p *GetItemResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetItemResp(%+v)", *p)
}

type UpdateItemReq struct {
	ID   *int64  `thrift:"id,1,optional" json:"id,omitempty" path:"id"`
	Name *string `thrift:"name,2,optional" form:"name" json:"name,omitempty"`
}

func NewUpdateItemReq() *UpdateItemReq {
	return &UpdateItemReq{}
}

func (p *UpdateItemReq) InitDefault() {
}

var UpdateItemReq_ID_DEFAULT int64

func (p *UpdateItemReq) GetID() (v int64) {
	if !p.IsSetID() {
		return UpdateItemReq_ID_DEFAULT
	}
	return *p.ID
}

var UpdateItemReq_Name_DEFAULT string

func (p *UpdateItemReq) GetName() (v string) {
	if !p.IsSetName() {
		return UpdateItemReq_Name_DEFAULT
	}
	return *p.Name
}

func (p *UpdateItemReq) IsSetID() bool {
	return p.ID != nil
}

func (p *UpdateItemReq) IsSetName() bool {
	return p.Name != nil
}

func (p *UpdateItemReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateItemReq(%+v)", *p)
}

type UpdateItemResp struct {
	Base *BaseResponse `thrift:"base,1,optional" form:"base" json:"base,omitempty" query:"base"`
	Data *Item         `thrift:"data,2,optional" form:"data" json:"data,omitempty" query:"data"`
}

func NewUpdateItemResp() *UpdateItemResp {
	return &UpdateItemResp{}
}

func (p *UpdateItemResp) InitDefault() {
}

var UpdateItemResp_Base_DEFAULT *BaseResponse

func (p *UpdateItemResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return UpdateItemResp_Base_DEFAULT
	}
	return p.Base
}

var UpdateItemResp_Data_DEFAULT *Item

func (p *UpdateItemResp) GetData() (v *Item) {
	if !p.IsSetData() {
		return UpdateItemResp_Data_DEFAULT
	}
	return p.Data
}

func (p *UpdateItemResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpdateItemResp) IsSetData() bool {
	return p.Data != nil
}

func (p *UpdateItemResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateItemResp(%+v)", *p)
}

type DeleteItemReq struct {
	ID *int64 `thrift:"id,1,optional" json:"id,omitempty" path:"id"`
}

func NewDeleteItemReq() *DeleteItemReq {
	return &DeleteItemReq{}
}

func (p *DeleteItemReq) InitDefault() {
}

var DeleteItemReq_ID_DEFAULT int64

func (p *DeleteItemReq) GetID() (v int64) {
	if !p.IsSetID() {
		return DeleteItemReq_ID_DEFAULT
	}
	return *p.ID
}

func (p *DeleteItemReq) IsSetID() bool {
	return p.ID != nil
}

func (p *DeleteItemReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteItemReq(%+v)", *p)
}

type DeleteItemResp struct {
	Base *BaseResponse `thrift:"base,1,optional" form:"base" json:"base,omitempty" query:"base"`
}

func NewDeleteItemResp() *DeleteItemResp {
	return &DeleteItemResp{}
}

func (p *DeleteItemResp) InitDefault() {
}

var DeleteItemResp_Base_DEFAULT *BaseResponse

func (p *DeleteItemResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return DeleteItemResp_Base_DEFAULT
	}
	return p.Base
}

func (p *DeleteItemResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *DeleteItemResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteItemResp(%+v)", *p)
}

type ListItemsReq struct {
	Page  *int32  `thrift:"page,1,optional" json:"page,omitempty" query:"page"`
	Limit *int32  `thrift:"limit,2,optional" json:"limit,omitempty" query:"limit"`
	Name  *string `thrift:"name,3,optional" json:"name,omitempty" query:"name"`
}

func NewListItemsReq() *ListItemsReq {
	return &ListItemsReq{}
}

func (p *ListItemsReq) InitDefault() {
}

var ListItemsReq_Page_DEFAULT int32

func (p *ListItemsReq) GetPage() (v int32) {
	if !p.IsSetPage() {
		return ListItemsReq_Page_DEFAULT
	}
	return *p.Page
}

var ListItemsReq_Limit_DEFAULT int32

func (p *ListItemsReq) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return ListItemsReq_Limit_DEFAULT
	}
	return *p.Limit
}

var ListItemsReq_Name_DEFAULT string

func (p *ListItemsReq) GetName() (v string) {
	if !p.IsSetName() {
		return ListItemsReq_Name_DEFAULT
	}
	return *p.Name
}

func (p *ListItemsReq) IsSetPage() bool {
	return p.Page != nil
}

func (p *ListItemsReq) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *ListItemsReq) IsSetName() bool {
	return p.Name != nil
}

func (p *ListItemsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListItemsReq(%+v)", *p)
}

type ListItemsResp struct {
	Base  *BaseResponse `thrift:"base,1,optional" form:"base" json:"base,omitempty" query:"base"`
	Data  []*Item       `thrift:"data,2,optional" form:"data" json:"data,omitempty" query:"data"`
	Total *int32        `thrift:"total,3,optional" form:"total" json:"total,omitempty" query:"total"`
}

func NewListItemsResp() *ListItemsResp {
	return &ListItemsResp{}
}

func (p *ListItemsResp) InitDefault() {
}

var ListItemsResp_Base_DEFAULT *BaseResponse

func (p *ListItemsResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return ListItemsResp_Base_DEFAULT
	}
	return p.Base
}

var ListItemsResp_Data_DEFAULT []*Item

func (p *ListItemsResp) GetData() (v []*Item) {
	if !p.IsSetData() {
		return ListItemsResp_Data_DEFAULT
	}
	return p.Data
}

var ListItemsResp_Total_DEFAULT int32

func (p *ListItemsResp) GetTotal() (v int32) {
	if !p.IsSetTotal() {
		return ListItemsResp_Total_DEFAULT
	}
	return *p.Total
}

func (p *ListItemsResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListItemsResp) IsSetData() bool {
	return p.Data != nil
}

func (p *ListItemsResp) IsSetTotal() bool {
	return p.Total != nil
}

func (p *ListItemsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListItemsResp(%+v)", *p)
}

// Recipe related structures
type Recipe struct {
	ID         *int64        `thrift:"id,1,optional" form:"id" json:"id,omitempty" query:"id"`
	Space      *int64        `thrift:"space,2,optional" form:"space" json:"space,omitempty" query:"space"`
	ItemID     *int64        `thrift:"item_id,3,optional" form:"item_id" json:"item_id,omitempty" query:"item_id"`
	ItemName   *string       `thrift:"item_name,4,optional" form:"item_name" json:"item_name,omitempty" query:"item_name"`
	Efficiency *float64      `thrift:"efficiency,5,optional" form:"efficiency" json:"efficiency,omitempty" query:"efficiency"`
	Items      []*RecipeItem `thrift:"items,16,optional" form:"items" json:"items,omitempty" query:"items"`
	CreatedAt  *string       `thrift:"created_at,32,optional" form:"created_at" json:"created_at,omitempty" query:"created_at"`
	UpdatedAt  *string       `thrift:"updated_at,33,optional" form:"updated_at" json:"updated_at,omitempty" query:"updated_at"`
}

func NewRecipe() *Recipe {
	return &Recipe{}
}

func (p *Recipe) InitDefault() {
}

var Recipe_ID_DEFAULT int64

func (p *Recipe) GetID() (v int64) {
	if !p.IsSetID() {
		return Recipe_ID_DEFAULT
	}
	return *p.ID
}

var Recipe_Space_DEFAULT int64

func (p *Recipe) GetSpace() (v int64) {
	if !p.IsSetSpace() {
		return Recipe_Space_DEFAULT
	}
	return *p.Space
}

var Recipe_ItemID_DEFAULT int64

func (p *Recipe) GetItemID() (v int64) {
	if !p.IsSetItemID() {
		return Recipe_ItemID_DEFAULT
	}
	return *p.ItemID
}

var Recipe_ItemName_DEFAULT string

func (p *Recipe) GetItemName() (v string) {
	if !p.IsSetItemName() {
		return Recipe_ItemName_DEFAULT
	}
	return *p.ItemName
}

var Recipe_Efficiency_DEFAULT float64

func (p *Recipe) GetEfficiency() (v float64) {
	if !p.IsSetEfficiency() {
		return Recipe_Efficiency_DEFAULT
	}
	return *p.Efficiency
}

var Recipe_Items_DEFAULT []*RecipeItem

func (p *Recipe) GetItems() (v []*RecipeItem) {
	if !p.IsSetItems() {
		return Recipe_Items_DEFAULT
	}
	return p.Items
}

var Recipe_CreatedAt_DEFAULT string

func (p *Recipe) GetCreatedAt() (v string) {
	if !p.IsSetCreatedAt() {
		return Recipe_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var Recipe_UpdatedAt_DEFAULT string

func (p *Recipe) GetUpdatedAt() (v string) {
	if !p.IsSetUpdatedAt() {
		return Recipe_UpdatedAt_DEFAULT
	}
	return *p.UpdatedAt
}

func (p *Recipe) IsSetID() bool {
	return p.ID != nil
}

func (p *Recipe) IsSetSpace() bool {
	return p.Space != nil
}

func (p *Recipe) IsSetItemID() bool {
	return p.ItemID != nil
}

func (p *Recipe) IsSetItemName() bool {
	return p.ItemName != nil
}

func (p *Recipe) IsSetEfficiency() bool {
	return p.Efficiency != nil
}

func (p *Recipe) IsSetItems() bool {
	return p.Items != nil
}

func (p *Recipe) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *Recipe) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *Recipe) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Recipe(%+v)", *p)
}

type RecipeItem struct {
	ID        *int64          `thrift:"id,1,optional" form:"id" json:"id,omitempty" query:"id"`
	RecipeID  *int64          `thrift:"recipe_id,2,optional" form:"recipe_id" json:"recipe_id,omitempty" query:"recipe_id"`
	Space     *int64          `thrift:"space,3,optional" form:"space" json:"space,omitempty" query:"space"`
	Type      *RecipeItemType `thrift:"type,4,optional" form:"type" json:"type,omitempty" query:"type"`
	Count     *int32          `thrift:"count,5,optional" form:"count" json:"count,omitempty" query:"count"`
	Item      *Item           `thrift:"item,6,optional" form:"item" json:"item,omitempty" query:"item"`
	CreatedAt *string         `thrift:"created_at,7,optional" form:"created_at" json:"created_at,omitempty" query:"created_at"`
	UpdatedAt *string         `thrift:"updated_at,8,optional" form:"updated_at" json:"updated_at,omitempty" query:"updated_at"`
}

func NewRecipeItem() *RecipeItem {
	return &RecipeItem{}
}

func (p *RecipeItem) InitDefault() {
}

var RecipeItem_ID_DEFAULT int64

func (p *RecipeItem) GetID() (v int64) {
	if !p.IsSetID() {
		return RecipeItem_ID_DEFAULT
	}
	return *p.ID
}

var RecipeItem_RecipeID_DEFAULT int64

func (p *RecipeItem) GetRecipeID() (v int64) {
	if !p.IsSetRecipeID() {
		return RecipeItem_RecipeID_DEFAULT
	}
	return *p.RecipeID
}

var RecipeItem_Space_DEFAULT int64

func (p *RecipeItem) GetSpace() (v int64) {
	if !p.IsSetSpace() {
		return RecipeItem_Space_DEFAULT
	}
	return *p.Space
}

var RecipeItem_Type_DEFAULT RecipeItemType

func (p *RecipeItem) GetType() (v RecipeItemType) {
	if !p.IsSetType() {
		return RecipeItem_Type_DEFAULT
	}
	return *p.Type
}

var RecipeItem_Count_DEFAULT int32

func (p *RecipeItem) GetCount() (v int32) {
	if !p.IsSetCount() {
		return RecipeItem_Count_DEFAULT
	}
	return *p.Count
}

var RecipeItem_Item_DEFAULT *Item

func (p *RecipeItem) GetItem() (v *Item) {
	if !p.IsSetItem() {
		return RecipeItem_Item_DEFAULT
	}
	return p.Item
}

var RecipeItem_CreatedAt_DEFAULT string

func (p *RecipeItem) GetCreatedAt() (v string) {
	if !p.IsSetCreatedAt() {
		return RecipeItem_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var RecipeItem_UpdatedAt_DEFAULT string

func (p *RecipeItem) GetUpdatedAt() (v string) {
	if !p.IsSetUpdatedAt() {
		return RecipeItem_UpdatedAt_DEFAULT
	}
	return *p.UpdatedAt
}

func (p *RecipeItem) IsSetID() bool {
	return p.ID != nil
}

func (p *RecipeItem) IsSetRecipeID() bool {
	return p.RecipeID != nil
}

func (p *RecipeItem) IsSetSpace() bool {
	return p.Space != nil
}

func (p *RecipeItem) IsSetType() bool {
	return p.Type != nil
}

func (p *RecipeItem) IsSetCount() bool {
	return p.Count != nil
}

func (p *RecipeItem) IsSetItem() bool {
	return p.Item != nil
}

func (p *RecipeItem) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *RecipeItem) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *RecipeItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecipeItem(%+v)", *p)
}

type CreateRecipeReq struct {
	Space      *int64        `thrift:"space,1,optional" form:"space" json:"space,omitempty"`
	ItemID     *int64        `thrift:"item_id,2,optional" form:"item_id" json:"item_id,omitempty"`
	Efficiency *float64      `thrift:"efficiency,3,optional" form:"efficiency" json:"efficiency,omitempty"`
	Items      []*RecipeItem `thrift:"items,4,optional" form:"items" json:"items,omitempty"`
}

func NewCreateRecipeReq() *CreateRecipeReq {
	return &CreateRecipeReq{}
}

func (p *CreateRecipeReq) InitDefault() {
}

var CreateRecipeReq_Space_DEFAULT int64

func (p *CreateRecipeReq) GetSpace() (v int64) {
	if !p.IsSetSpace() {
		return CreateRecipeReq_Space_DEFAULT
	}
	return *p.Space
}

var CreateRecipeReq_ItemID_DEFAULT int64

func (p *CreateRecipeReq) GetItemID() (v int64) {
	if !p.IsSetItemID() {
		return CreateRecipeReq_ItemID_DEFAULT
	}
	return *p.ItemID
}

var CreateRecipeReq_Efficiency_DEFAULT float64

func (p *CreateRecipeReq) GetEfficiency() (v float64) {
	if !p.IsSetEfficiency() {
		return CreateRecipeReq_Efficiency_DEFAULT
	}
	return *p.Efficiency
}

var CreateRecipeReq_Items_DEFAULT []*RecipeItem

func (p *CreateRecipeReq) GetItems() (v []*RecipeItem) {
	if !p.IsSetItems() {
		return CreateRecipeReq_Items_DEFAULT
	}
	return p.Items
}

func (p *CreateRecipeReq) IsSetSpace() bool {
	return p.Space != nil
}

func (p *CreateRecipeReq) IsSetItemID() bool {
	return p.ItemID != nil
}

func (p *CreateRecipeReq) IsSetEfficiency() bool {
	return p.Efficiency != nil
}

func (p *CreateRecipeReq) IsSetItems() bool {
	return p.Items != nil
}

func (p *CreateRecipeReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateRecipeReq(%+v)", *p)
}

type CreateRecipeResp struct {
	Base *BaseResponse `thrift:"base,1,optional" form:"base" json:"base,omitempty" query:"base"`
	Data *Recipe       `thrift:"data,2,optional" form:"data" json:"data,omitempty" query:"data"`
}

func NewCreateRecipeResp() *CreateRecipeResp {
	return &CreateRecipeResp{}
}

func (p *CreateRecipeResp) InitDefault() {
}

var CreateRecipeResp_Base_DEFAULT *BaseResponse

func (p *CreateRecipeResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return CreateRecipeResp_Base_DEFAULT
	}
	return p.Base
}

var CreateRecipeResp_Data_DEFAULT *Recipe

func (p *CreateRecipeResp) GetData() (v *Recipe) {
	if !p.IsSetData() {
		return CreateRecipeResp_Data_DEFAULT
	}
	return p.Data
}

func (p *CreateRecipeResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *CreateRecipeResp) IsSetData() bool {
	return p.Data != nil
}

func (p *CreateRecipeResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateRecipeResp(%+v)", *p)
}

type GetRecipeReq struct {
	ID *int64 `thrift:"id,1,optional" json:"id,omitempty" path:"id"`
}

func NewGetRecipeReq() *GetRecipeReq {
	return &GetRecipeReq{}
}

func (p *GetRecipeReq) InitDefault() {
}

var GetRecipeReq_ID_DEFAULT int64

func (p *GetRecipeReq) GetID() (v int64) {
	if !p.IsSetID() {
		return GetRecipeReq_ID_DEFAULT
	}
	return *p.ID
}

func (p *GetRecipeReq) IsSetID() bool {
	return p.ID != nil
}

func (p *GetRecipeReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetRecipeReq(%+v)", *p)
}

type GetRecipeResp struct {
	Base *BaseResponse `thrift:"base,1,optional" form:"base" json:"base,omitempty" query:"base"`
	Data *Recipe       `thrift:"data,2,optional" form:"data" json:"data,omitempty" query:"data"`
}

func NewGetRecipeResp() *GetRecipeResp {
	return &GetRecipeResp{}
}

func (p *GetRecipeResp) InitDefault() {
}

var GetRecipeResp_Base_DEFAULT *BaseResponse

func (p *GetRecipeResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return GetRecipeResp_Base_DEFAULT
	}
	return p.Base
}

var GetRecipeResp_Data_DEFAULT *Recipe

func (p *GetRecipeResp) GetData() (v *Recipe) {
	if !p.IsSetData() {
		return GetRecipeResp_Data_DEFAULT
	}
	return p.Data
}

func (p *GetRecipeResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetRecipeResp) IsSetData() bool {
	return p.Data != nil
}

func (p *GetRecipeResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetRecipeResp(%+v)", *p)
}

type UpdateRecipeReq struct {
	Data *Recipe `thrift:"data,1,optional" form:"data" json:"data,omitempty" query:"data"`
}

func NewUpdateRecipeReq() *UpdateRecipeReq {
	return &UpdateRecipeReq{}
}

func (p *UpdateRecipeReq) InitDefault() {
}

var UpdateRecipeReq_Data_DEFAULT *Recipe

func (p *UpdateRecipeReq) GetData() (v *Recipe) {
	if !p.IsSetData() {
		return UpdateRecipeReq_Data_DEFAULT
	}
	return p.Data
}

func (p *UpdateRecipeReq) IsSetData() bool {
	return p.Data != nil
}

func (p *UpdateRecipeReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateRecipeReq(%+v)", *p)
}

type UpdateRecipeResp struct {
	Base *BaseResponse `thrift:"base,1,optional" form:"base" json:"base,omitempty" query:"base"`
	Data *Recipe       `thrift:"data,2,optional" form:"data" json:"data,omitempty" query:"data"`
}

func NewUpdateRecipeResp() *UpdateRecipeResp {
	return &UpdateRecipeResp{}
}

func (p *UpdateRecipeResp) InitDefault() {
}

var UpdateRecipeResp_Base_DEFAULT *BaseResponse

func (p *UpdateRecipeResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return UpdateRecipeResp_Base_DEFAULT
	}
	return p.Base
}

var UpdateRecipeResp_Data_DEFAULT *Recipe

func (p *UpdateRecipeResp) GetData() (v *Recipe) {
	if !p.IsSetData() {
		return UpdateRecipeResp_Data_DEFAULT
	}
	return p.Data
}

func (p *UpdateRecipeResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpdateRecipeResp) IsSetData() bool {
	return p.Data != nil
}

func (p *UpdateRecipeResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateRecipeResp(%+v)", *p)
}

type DeleteRecipeReq struct {
	ID *int64 `thrift:"id,1,optional" json:"id,omitempty" path:"id"`
}

func NewDeleteRecipeReq() *DeleteRecipeReq {
	return &DeleteRecipeReq{}
}

func (p *DeleteRecipeReq) InitDefault() {
}

var DeleteRecipeReq_ID_DEFAULT int64

func (p *DeleteRecipeReq) GetID() (v int64) {
	if !p.IsSetID() {
		return DeleteRecipeReq_ID_DEFAULT
	}
	return *p.ID
}

func (p *DeleteRecipeReq) IsSetID() bool {
	return p.ID != nil
}

func (p *DeleteRecipeReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteRecipeReq(%+v)", *p)
}

type DeleteRecipeResp struct {
	Base *BaseResponse `thrift:"base,1,optional" form:"base" json:"base,omitempty" query:"base"`
}

func NewDeleteRecipeResp() *DeleteRecipeResp {
	return &DeleteRecipeResp{}
}

func (p *DeleteRecipeResp) InitDefault() {
}

var DeleteRecipeResp_Base_DEFAULT *BaseResponse

func (p *DeleteRecipeResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return DeleteRecipeResp_Base_DEFAULT
	}
	return p.Base
}

func (p *DeleteRecipeResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *DeleteRecipeResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteRecipeResp(%+v)", *p)
}

type ListRecipesReq struct {
	Page   *int32 `thrift:"page,1,optional" json:"page,omitempty" query:"page"`
	Limit  *int32 `thrift:"limit,2,optional" json:"limit,omitempty" query:"limit"`
	Space  *int64 `thrift:"space,3,optional" json:"space,omitempty" query:"space"`
	ItemID *int64 `thrift:"item_id,4,optional" json:"item_id,omitempty" query:"item_id"`
}

func NewListRecipesReq() *ListRecipesReq {
	return &ListRecipesReq{}
}

func (p *ListRecipesReq) InitDefault() {
}

var ListRecipesReq_Page_DEFAULT int32

func (p *ListRecipesReq) GetPage() (v int32) {
	if !p.IsSetPage() {
		return ListRecipesReq_Page_DEFAULT
	}
	return *p.Page
}

var ListRecipesReq_Limit_DEFAULT int32

func (p *ListRecipesReq) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return ListRecipesReq_Limit_DEFAULT
	}
	return *p.Limit
}

var ListRecipesReq_Space_DEFAULT int64

func (p *ListRecipesReq) GetSpace() (v int64) {
	if !p.IsSetSpace() {
		return ListRecipesReq_Space_DEFAULT
	}
	return *p.Space
}

var ListRecipesReq_ItemID_DEFAULT int64

func (p *ListRecipesReq) GetItemID() (v int64) {
	if !p.IsSetItemID() {
		return ListRecipesReq_ItemID_DEFAULT
	}
	return *p.ItemID
}

func (p *ListRecipesReq) IsSetPage() bool {
	return p.Page != nil
}

func (p *ListRecipesReq) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *ListRecipesReq) IsSetSpace() bool {
	return p.Space != nil
}

func (p *ListRecipesReq) IsSetItemID() bool {
	return p.ItemID != nil
}

func (p *ListRecipesReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListRecipesReq(%+v)", *p)
}

type ListRecipesResp struct {
	Base  *BaseResponse `thrift:"base,1,optional" form:"base" json:"base,omitempty" query:"base"`
	Data  []*Recipe     `thrift:"data,2,optional" form:"data" json:"data,omitempty" query:"data"`
	Total *int32        `thrift:"total,3,optional" form:"total" json:"total,omitempty" query:"total"`
}

func NewListRecipesResp() *ListRecipesResp {
	return &ListRecipesResp{}
}

func (p *ListRecipesResp) InitDefault() {
}

var ListRecipesResp_Base_DEFAULT *BaseResponse

func (p *ListRecipesResp) GetBase() (v *BaseResponse) {
	if !p.IsSetBase() {
		return ListRecipesResp_Base_DEFAULT
	}
	return p.Base
}

var ListRecipesResp_Data_DEFAULT []*Recipe

func (p *ListRecipesResp) GetData() (v []*Recipe) {
	if !p.IsSetData() {
		return ListRecipesResp_Data_DEFAULT
	}
	return p.Data
}

var ListRecipesResp_Total_DEFAULT int32

func (p *ListRecipesResp) GetTotal() (v int32) {
	if !p.IsSetTotal() {
		return ListRecipesResp_Total_DEFAULT
	}
	return *p.Total
}

func (p *ListRecipesResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListRecipesResp) IsSetData() bool {
	return p.Data != nil
}

func (p *ListRecipesResp) IsSetTotal() bool {
	return p.Total != nil
}

func (p *ListRecipesResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListRecipesResp(%+v)", *p)
}

// Service definitions
type ItemService interface {
	CreateItem(ctx context.Context, request *CreateItemReq) (r *CreateItemResp, err error)

	GetItem(ctx context.Context, request *GetItemReq) (r *GetItemResp, err error)

	UpdateItem(ctx context.Context, request *UpdateItemReq) (r *UpdateItemResp, err error)

	DeleteItem(ctx context.Context, request *DeleteItemReq) (r *DeleteItemResp, err error)

	ListItems(ctx context.Context, request *ListItemsReq) (r *ListItemsResp, err error)
}

type RecipeService interface {
	CreateRecipe(ctx context.Context, request *CreateRecipeReq) (r *CreateRecipeResp, err error)

	GetRecipe(ctx context.Context, request *GetRecipeReq) (r *GetRecipeResp, err error)

	UpdateRecipe(ctx context.Context, request *UpdateRecipeReq) (r *UpdateRecipeResp, err error)

	DeleteRecipe(ctx context.Context, request *DeleteRecipeReq) (r *DeleteRecipeResp, err error)

	ListRecipes(ctx context.Context, request *ListRecipesReq) (r *ListRecipesResp, err error)
}
