// Code generated by hertz generator.

package handler

import (
	"context"
	"fmt"

	"code.byted.org/lang/gg/gslice"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/richsoap/RecipeCalculator/biz/convert"
	api "github.com/richsoap/RecipeCalculator/biz/model/recipe/api"
	"github.com/richsoap/RecipeCalculator/dal/gen"
	"github.com/richsoap/RecipeCalculator/dal/model"
	"github.com/richsoap/RecipeCalculator/errors"
)

// CreateRecipe 创建配方
// @router /api/v1/recipes [POST]
func CreateRecipe(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CreateRecipeReq
	// 绑定并验证请求参数
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, herr := DoCreateRecipe(ctx, &req)
	if herr != nil {
		c.String(herr.HTTPCode(), herr.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

func DoCreateRecipe(ctx context.Context, req *api.CreateRecipeReq) (*api.CreateRecipeResp, *errors.HTTPCodeErr) {
	// 提取所有相关物品ID
	ids := gslice.Map(req.GetItems(), (func(item *api.RecipeItem) int64 {
		return item.GetItem().GetID()
	}))
	ids = append(ids, req.GetItemID())

	// 查询所有相关物品
	items, err := gen.Item.WithContext(ctx).Where(gen.Item.ID.In(ids...)).Find()
	if err != nil {
		return nil, &errors.HTTPCodeErr{
			Code: consts.StatusBadRequest,
			Err:  err,
		}
	}

	// 构建物品ID映射
	itemMap := gslice.ToMapValues(items, func(item *model.Item) int64 {
		return item.ID
	})

	// 验证所有物品是否存在
	for _, id := range ids {
		if _, ok := itemMap[id]; !ok {
			return nil, &errors.HTTPCodeErr{
				Code: consts.StatusBadRequest,
				Err:  fmt.Errorf("recipe item not found: %d", id),
			}
		}
	}

	// 创建配方记录
	recipe := &model.Recipe{
		Space:      int32(req.GetSpace()),
		ItemID:     req.GetItemID(),
		Efficiency: req.GetEfficiency(),
	}
	err = gen.Recipe.WithContext(ctx).Create(recipe)
	if err != nil {
		return nil, &errors.HTTPCodeErr{
			Code: consts.StatusBadRequest,
			Err:  fmt.Errorf("create recipe failed, err: %v", err),
		}
	}

	// 创建配方物品关联记录
	recipeItems := gslice.Map(req.GetItems(), (func(item *api.RecipeItem) *model.RecipeItem {
		return &model.RecipeItem{
			RecipeID: recipe.ID,
			ItemID:   item.GetItem().GetID(),
			Count_:   item.GetCount(),
		}
	}))
	err = gen.RecipeItem.WithContext(ctx).Create(recipeItems...)
	if err != nil {
		return nil, &errors.HTTPCodeErr{
			Code: consts.StatusBadRequest,
			Err:  fmt.Errorf("create recipe item failed, err: %v", err),
		}
	}

	// 构建响应数据
	resp := new(api.CreateRecipeResp)
	resp.Data = convert.ConvertRecipeToApi(recipe)
	resp.Data.Items = gslice.Map(recipeItems, (func(item *model.RecipeItem) *api.RecipeItem {
		return convert.ConvertRecipeItemToApi(item, itemMap[item.ItemID])
	}))
	return resp, nil
}
