// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/richsoap/RecipeCalculator/biz/convert"
	api "github.com/richsoap/RecipeCalculator/biz/model/recipe/api"
	"github.com/richsoap/RecipeCalculator/dal/gen"
	"github.com/richsoap/RecipeCalculator/dal/model"
)

// CreateItem .
// @router /api/v1/items [POST]
func CreateItem(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CreateItemReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	m := &model.Item{
		Name: req.GetName(),
	}
	err = gen.Item.WithContext(ctx).Create(m)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.CreateItemResp)
	resp.Data = convert.ConvertItemToApi(m)

	c.JSON(consts.StatusOK, resp)
}
