// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/richsoap/RecipeCalculator/biz/model/recipe/api"
	"github.com/richsoap/RecipeCalculator/dal/gen"
)

// DeleteItem .
// @router /api/v1/items/:id [DELETE]
func DeleteItem(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DeleteItemReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	_, err = gen.Item.WithContext(ctx).Where(gen.Item.ID.Eq(req.GetID())).Delete()
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.DeleteItemResp)

	c.JSON(consts.StatusOK, resp)
}
