// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/richsoap/RecipeCalculator/biz/convert"
	api "github.com/richsoap/RecipeCalculator/biz/model/recipe/api"
	"github.com/richsoap/RecipeCalculator/dal/gen"
)

// GetItem .
// @router /api/v1/items/:id [GET]
func GetItem(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetItemReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	m, err := gen.Item.WithContext(ctx).Where(gen.Item.ID.Eq(req.GetID())).First()
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.GetItemResp)
	resp.Data = convert.ConvertItemToApi(m)

	c.JSON(consts.StatusOK, resp)
}
