// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/richsoap/RecipeCalculator/biz/model/recipe/api"
)

// ListRecipes .
// @router /api/v1/recipes [GET]
func ListRecipes(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ListRecipesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.ListRecipesResp)

	c.JSON(consts.StatusOK, resp)
}
