// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRecipe = "recipes"

// Recipe mapped from table <recipes>
type Recipe struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Space      int32     `gorm:"column:space;not null" json:"space"`
	ItemID     int64     `gorm:"column:item_id;not null" json:"item_id"`
	Efficiency float64   `gorm:"column:efficiency;not null;default:1.0" json:"efficiency"`
	CreatedAt  time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Recipe's table name
func (*Recipe) TableName() string {
	return TableNameRecipe
}
