// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/richsoap/RecipeCalculator/biz/model/recipe/api"
)

// CreateItem .
// @router /api/v1/items [POST]
func CreateItem(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CreateItemReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.CreateItemResp)

	c.JSON(consts.StatusOK, resp)
}

// GetItem .
// @router /api/v1/items/:id [GET]
func GetItem(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetItemReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.GetItemResp)

	c.JSON(consts.StatusOK, resp)
}

// UpdateItem .
// @router /api/v1/items/:id [PUT]
func UpdateItem(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UpdateItemReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.UpdateItemResp)

	c.JSON(consts.StatusOK, resp)
}

// DeleteItem .
// @router /api/v1/items/:id [DELETE]
func DeleteItem(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DeleteItemReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.DeleteItemResp)

	c.JSON(consts.StatusOK, resp)
}

// ListItems .
// @router /api/v1/items [GET]
func ListItems(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ListItemsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.ListItemsResp)

	c.JSON(consts.StatusOK, resp)
}
