// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/richsoap/RecipeCalculator/biz/model/recipe/api"
)

// CreateRecipe .
// @router /api/v1/recipes [POST]
func CreateRecipe(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CreateRecipeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.CreateRecipeResp)

	c.JSON(consts.StatusOK, resp)
}

// GetRecipe .
// @router /api/v1/recipes/:id [GET]
func GetRecipe(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetRecipeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.GetRecipeResp)

	c.JSON(consts.StatusOK, resp)
}

// UpdateRecipe .
// @router /api/v1/recipes/:id [PUT]
func UpdateRecipe(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UpdateRecipeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.UpdateRecipeResp)

	c.JSON(consts.StatusOK, resp)
}

// DeleteRecipe .
// @router /api/v1/recipes/:id [DELETE]
func DeleteRecipe(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DeleteRecipeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.DeleteRecipeResp)

	c.JSON(consts.StatusOK, resp)
}

// ListRecipes .
// @router /api/v1/recipes [GET]
func ListRecipes(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ListRecipesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.ListRecipesResp)

	c.JSON(consts.StatusOK, resp)
}
